import React from 'react';
import { SEOHead } from '../../components/ui/SEOHead';
import { Calendar } from 'lucide-react';

export function Terms() {
  return (
    <>
      <SEOHead 
        title="Terms of Service"
        description="Lovable Terms of Service and user agreement"
        canonical="https://lovable.dev/legal/terms"
      />
      
      <div className="py-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">
              Terms of Service
            </h1>
            <div className="flex items-center justify-center text-gray-600">
              <Calendar className="h-4 w-4 mr-2" />
              <span>Last updated: January 15, 2024</span>
            </div>
          </div>

          <div className="prose prose-lg max-w-none">
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">
              <p className="text-blue-800 mb-0">
                <strong>Important:</strong> These terms govern your use of Lovable's AI-powered development platform. 
                By using our service, you agree to these terms.
              </p>
            </div>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using Lovable ("the Service"), you accept and agree to be bound by the terms 
              and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              Lovable is an AI-powered development platform that enables users to create applications through 
              natural language conversations with artificial intelligence. The Service includes:
            </p>
            <ul>
              <li>AI-powered code generation and editing</li>
              <li>Real-time collaboration tools</li>
              <li>Project management and deployment features</li>
              <li>Integration with third-party services</li>
            </ul>

            <h2>3. User Accounts</h2>
            <p>
              To access certain features of the Service, you must register for an account. You agree to:
            </p>
            <ul>
              <li>Provide accurate and complete information during registration</li>
              <li>Maintain the security of your password and account</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>

            <h2>4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Generate malicious, harmful, or illegal content</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the Service</li>
            </ul>

            <h2>5. Intellectual Property</h2>
            <p>
              You retain ownership of the code and content you create using Lovable. However, you grant us 
              a limited license to process and analyze your content to provide and improve the Service.
            </p>
            <p>
              Lovable and its original content, features, and functionality are owned by Lovable and are 
              protected by international copyright, trademark, patent, trade secret, and other intellectual 
              property laws.
            </p>

            <h2>6. AI-Generated Content</h2>
            <p>
              Content generated by our AI systems is provided "as is" without warranties. You are responsible for:
            </p>
            <ul>
              <li>Reviewing and testing all AI-generated code</li>
              <li>Ensuring compliance with applicable laws and regulations</li>
              <li>Respecting third-party intellectual property rights</li>
              <li>Understanding that AI outputs may contain errors or biases</li>
            </ul>

            <h2>7. Privacy and Data</h2>
            <p>
              Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect 
              your information when you use the Service. By using the Service, you agree to the collection 
              and use of information in accordance with our Privacy Policy.
            </p>

            <h2>8. Subscription and Billing</h2>
            <p>
              Some features of the Service require a paid subscription. By subscribing, you agree to:
            </p>
            <ul>
              <li>Pay all applicable fees as described in your subscription plan</li>
              <li>Automatic renewal unless cancelled</li>
              <li>Our refund policy as stated in your subscription terms</li>
            </ul>

            <h2>9. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service immediately, without prior 
              notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
            </p>

            <h2>10. Disclaimers</h2>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties, 
              whether express or implied, including but not limited to implied warranties of merchantability, 
              fitness for a particular purpose, and non-infringement.
            </p>

            <h2>11. Limitation of Liability</h2>
            <p>
              In no event shall Lovable be liable for any indirect, incidental, special, consequential, or 
              punitive damages, including without limitation, loss of profits, data, use, goodwill, or other 
              intangible losses.
            </p>

            <h2>12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users of any material 
              changes via email or through the Service. Your continued use of the Service after such 
              modifications constitutes acceptance of the updated terms.
            </p>

            <h2>13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of [Jurisdiction], 
              without regard to its conflict of law provisions.
            </p>

            <h2>14. Contact Information</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <ul>
              <li>Email: legal@lovable.dev</li>
              <li>Address: [Company Address]</li>
            </ul>
          </div>

          <div className="mt-12 p-6 bg-gray-50 rounded-lg">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Questions?</h3>
            <p className="text-gray-600 mb-4">
              If you have any questions about these terms, please don't hesitate to contact our legal team.
            </p>
            <a
              href="mailto:legal@lovable.dev"
              className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
            >
              Contact Legal Team
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
